# Generated by Django 5.2.12 on 2026-03-08 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Admin", "Admin"),
                            ("Author", "Author"),
                            ("Reviewer", "Reviewer"),
                        ],
                        help_text="The role type (Admin, Author, Reviewer)",
                        max_length=20,
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
